name: Lint

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    if: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install packages to tests
        run: pip install ./psycopg[dev,test]

      - name: Run black
        run: black --check --diff .

      - name: Run flake8
        run: flake8

      - name: Run mypy
        run: mypy

      - name: Check for sync/async inconsistencies
        run: ./tools/async_to_sync.py --check --all

      - name: Check spelling
        run: codespell

      - name: Install requirements to generate docs
        run: sudo apt-get install -y libgeos-dev

      - name: Install Python packages to generate docs
        run: pip install ./psycopg[docs] ./psycopg_pool

      - name: Check documentation
        run: sphinx-build -W -T -b html docs docs/_build/html
